---
all:
  vars:
    ambiente: virtualbox
    ansible_ssh_private_key_file: ./keys/registry

  hosts:
    registry-virtualbox:
      ansible_host: 192.168.10.30

  children:
    registry:
      hosts:
        registry-virtualbox: