---
- name: Criar pasta de certificados
  file:
    state: directory
    path: /home/vagrant/registry/certs

- name: Gerar chave privada
  openssl_privatekey:
    path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.key
    size: 2048 

- name: Gerar csr
  openssl_csr:
    path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.csr
    privatekey_path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.key

- name: Gerar certificado
  openssl_certificate:
    provider: selfsigned
    path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.crt
    privatekey_path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.key
    csr_path: /home/vagrant/registry/certs/registry.{{ambiente}}.infra.csr